### PR TITLE
Preserve local npmrc file

### PR DESCRIPTION
**Pull request by bcomnes**
When using a local .npmrc file, preserve the contents. Useful when using GitHub private registry.

### CODE REVIEW

**Comment by bcomnes** [comment]
@mafintosh thoughts? would love to land this.  Happy to help with release/maint perms if you would prefer that instead.

**Comment by mafintosh** [comment]
Ah makes sense!

**Comment by mafintosh** [comment]
Ya let me add you.

**Comment by mafintosh** [comment]
I think I added you to both npm and github now

**Comment by bcomnes** [comment]
Sweet! ill set up a release and monitor for any issues!

**Comment by bcomnes** [comment]
Looks like my npm account (bret) doesn't have perms. Maybe you added bcomnes which is just a security placeholder account?  Sorry :( I should re-mention that anytime I coordinate this.

**Comment by mafintosh** [comment]
I added bret through the website, let me do it through the cli

**Comment by mafintosh** [comment]
try again

**Comment by bcomnes** [comment]
🎉 update-package-lock@1.1.0 🎉

**Pull request merged**
